import type { LocalizedText, Locale } from "@sp/types";

export const L = (az: string, ru?: string, en?: string): LocalizedText => ({ az, ru: ru ?? az, en: en ?? az });

export function tr(text: LocalizedText | string | null | undefined, locale: Locale): string {
  if (!text) return "";
  if (typeof text === "string") return text;
  return text[locale] || text.az;
}

export function localeFromRequest(request: Request): Locale {
  const header = request.headers.get("accept-language") ?? "az";
  const first = header.split(",")[0]!.trim().slice(0, 2).toLowerCase();
  return first === "ru" || first === "en" ? first : "az";
}

/** Small server-side dictionary for strings generated by the mock backend (messages, labels). */
const dict: Record<string, LocalizedText> = {
  "error.unauthorized": L("Sistemə daxil olmalısınız", "Необходимо войти в систему", "You need to sign in"),
  "error.forbidden": L("Bu əməliyyat üçün icazəniz yoxdur", "Недостаточно прав для этой операции", "You don't have permission for this action"),
  "error.notFound": L("Məlumat tapılmadı", "Данные не найдены", "Not found"),
  "error.validation": L("Məlumatlarda xəta var", "Ошибка в данных", "Validation failed"),
  "error.server": L("Serverdə gözlənilməz xəta baş verdi", "Непредвиденная ошибка сервера", "Unexpected server error"),
  "error.invalidCredentials": L("E-poçt və ya şifrə yanlışdır", "Неверный e-mail или пароль", "Invalid email or password"),
  "error.invalidOtp": L("Kod yanlışdır və ya müddəti bitib", "Код неверный или истёк", "Code is invalid or expired"),
  "error.userNotFound": L("Bu nömrə ilə hesab tapılmadı", "Аккаунт с этим номером не найден", "No account found for this number"),
  "error.alreadyExists": L("Bu məlumatla hesab artıq mövcuddur", "Аккаунт с такими данными уже существует", "An account with these details already exists"),
  "error.entitlement": L("Planınız bu imkanı dəstəkləmir", "Ваш план не поддерживает эту возможность", "Your plan doesn't include this feature"),
  "error.limit": L("Plan limitinə çatmısınız", "Достигнут лимит плана", "Plan limit reached"),
  "error.actionNotAllowed": L("Bu status üçün əməliyyat mümkün deyil", "Операция недоступна в текущем статусе", "Action isn't available in the current status"),
  "error.stock": L("Stokda kifayət qədər məhsul yoxdur", "Недостаточно товара на складе", "Insufficient stock"),
  "error.promo": L("Promo kod etibarsızdır", "Промокод недействителен", "Promo code is invalid"),
  "error.requirements": L("Mərhələnin tamamlanma tələbləri ödənməyib", "Не выполнены требования завершения этапа", "Stage completion requirements are not met"),
  "error.templateInvalid": L("Şablon yoxlamadan keçmədi", "Шаблон не прошёл проверку", "Template validation failed"),
  "error.mock": L("Simulyasiya olunmuş server xətası", "Симулированная ошибка сервера", "Simulated server error"),
  "delivery.courier": L("Kuryerlə çatdırılma", "Доставка курьером", "Courier delivery"),
  "delivery.pickup": L("Filialdan götürmə", "Самовывоз из филиала", "Pick up at branch"),
  "delivery.withInstallation": L("Quraşdırma ilə birlikdə", "Вместе с установкой", "Together with installation"),
  "eta.tomorrow": L("Sabah", "Завтра", "Tomorrow"),
  "eta.2days": L("1–2 iş günü", "1–2 рабочих дня", "1–2 business days"),
  "eta.install": L("Quraşdırma vaxtında", "Во время установки", "At installation time"),
  "eta.today": L("Bu gün", "Сегодня", "Today"),
  "pay.cash": L("Nağd (çatdırılmada)", "Наличными (при получении)", "Cash on delivery"),
  "pay.card": L("Kartla onlayn", "Картой онлайн", "Card online"),
  "pay.pos": L("POS terminal (çatdırılmada)", "POS-терминал (при получении)", "POS terminal on delivery"),
  "pay.transfer": L("Bank köçürməsi", "Банковский перевод", "Bank transfer"),
  "pay.installment": L("Taksit kartı", "Карта рассрочки", "Installment card"),
  "pay.balance": L("Balans / kredit limiti", "Баланс / кредитный лимит", "Balance / credit limit"),
  "pay.b2bOnly": L("Yalnız B2B hesabları üçün", "Только для B2B-аккаунтов", "B2B accounts only"),
  "pay.installmentMin": L("300 AZN-dən yuxarı sifarişlər üçün", "Для заказов от 300 AZN", "For orders over 300 AZN"),
  "discount.subscription": L("Abunə endirimi", "Скидка по подписке", "Subscription discount"),
  "discount.skippedExclusive": L("Eksklüziv kampaniya ilə birləşmir", "Не суммируется с эксклюзивной акцией", "Not combinable with an exclusive campaign"),
  "discount.skippedList": L("Bu kampaniya ilə birləşmə icazəsi yoxdur", "Не разрешено сочетание с этой акцией", "Not allowed together with this campaign"),
  "discount.capped": L("Maksimum endirim həddi tətbiq olundu", "Применён лимит максимальной скидки", "Maximum discount cap applied"),
  "cart.priceChanged": L("Qiymət dəyişib", "Цена изменилась", "Price has changed"),
  "cart.stockLow": L("Stokda az qalıb", "Осталось мало", "Low stock"),
  "cart.outOfStock": L("Stokda yoxdur", "Нет в наличии", "Out of stock"),
  "fee.none": L("Smetanı qəbul etmədikdə diaqnostika haqqı tutulmur", "При отказе от сметы плата за диагностику не взимается", "No diagnostics fee if you decline the estimate"),
  "terms.cancel": L("Ləğv pulsuzdur. Usta yola çıxdıqdan sonra ləğv edilərsə çağırış haqqı tətbiq oluna bilər.", "Отмена бесплатна. После выезда мастера может взиматься плата за вызов.", "Cancellation is free. A call-out fee may apply once the technician is on the way."),
  "return.cutToLength": L("Ölçüyə görə kəsilmiş məhsul geri qaytarılmır", "Товар, отрезанный по размеру, возврату не подлежит", "Cut-to-length products can't be returned"),
  "return.installed": L("Quraşdırılmış məhsulun qaytarılması məhduddur", "Возврат установленного товара ограничен", "Returns are limited once installed"),
  "notif.orderCreated": L("Sifariş yaradıldı", "Заказ создан", "Order created"),
  "notif.estimateReady": L("Smeta hazırdır", "Смета готова", "Estimate is ready"),
  "notif.technicianAssigned": L("Usta təyin olundu", "Мастер назначен", "Technician assigned"),
  "notif.technicianOnWay": L("Usta yoldadır", "Мастер в пути", "Technician is on the way"),
  "notif.deviceReady": L("Cihazınız hazırdır", "Ваше устройство готово", "Your device is ready"),
  "notif.paymentOk": L("Ödəniş uğurla tamamlandı", "Оплата прошла успешно", "Payment successful"),
  "notif.paymentFail": L("Ödəniş uğursuz oldu", "Оплата не прошла", "Payment failed"),
  "notif.newOffer": L("Yeni iş təklifi", "Новое предложение работы", "New job offer"),
  "notif.newTask": L("Yeni logistika tapşırığı", "Новая логистическая задача", "New logistics task"),
  "notif.orderCompleted": L("Servis tamamlandı", "Сервис завершён", "Service completed"),
  "notif.orderConfirmed": L("Sifariş təsdiqləndi", "Заказ подтверждён", "Order confirmed"),
  "notif.subscriptionRenewal": L("Abunəlik yenilənəcək", "Продление подписки", "Subscription renewal"),
  "notif.serviceDue": L("Periodik servis vaxtıdır", "Пора плановому обслуживанию", "Periodic service due"),
  "notif.settlementApproved": L("Hesablaşma təsdiqləndi", "Выплата одобрена", "Settlement approved"),
  "notif.lowStock": L("Aşağı stok xəbərdarlığı", "Низкий остаток", "Low stock alert"),
  "notif.slaBreach": L("SLA pozuntusu", "Нарушение SLA", "SLA breach"),
  "notif.lowRating": L("Aşağı reytinqli rəy", "Отзыв с низкой оценкой", "Low-rated review"),
  "notif.documentExpiring": L("Sənədin müddəti bitib", "Истёк срок документа", "Document expired"),
  "notif.warrantyApproved": L("Zəmanət müraciəti təsdiqləndi", "Гарантийное обращение одобрено", "Warranty claim approved"),
  "notif.ticketCreated": L("Müraciətiniz qəbul edildi", "Обращение принято", "Request received"),
  "notif.ticketNew": L("Yeni müraciət", "Новое обращение", "New ticket"),
  "notif.ticketAssigned": L("Müraciət sizə təyin olundu", "Вам назначено обращение", "Ticket assigned to you"),
  "notif.ticketReply": L("Dəstək xidmətindən cavab", "Ответ службы поддержки", "Reply from support"),
  "notif.ticketCustomerReply": L("Müştəri cavab yazdı", "Клиент ответил", "Customer replied"),
  "notif.ticketReopened": L("Müraciət yenidən açıldı", "Обращение переоткрыто", "Ticket reopened"),
  "notif.ticketResolved": L("Müraciətiniz həll olundu", "Обращение решено", "Your request is resolved"),
  "notif.ticketEscalated": L("Müraciət eskalasiya olundu", "Эскалация обращения", "Ticket escalated"),
  "notif.ticketSlaBreach": L("Müraciətin SLA-sı pozuldu", "Нарушен SLA обращения", "Ticket SLA breached"),
};

export function t(key: string, locale: Locale, vars?: Record<string, string | number>): string {
  let s = tr(dict[key], locale) || key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v));
  return s;
}
